### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by dsoronda** [ParsePlatform/AnyBlog#6]
Readme documentation is old and incorrect for current version of parse.com

I followed all steps and got this error on my site :

Failed loading posts

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by hramos** [comment]
Should be fixed now! #11
