### ISSUE TITLE
CSS Error

### ISSUE THREAD

**Issue by vireshmanagooli** [ParsePlatform/AnyBlog#9]
I have followed all the steps given in README file. When I opened it in my subdomain.parse.com, webpage is getting distorted. when i checked in the console, I could see the following error. 

- <b>CSS Error</b> Resource interpreted as Stylesheet but transferred with MIME type text/plain

Do we need to do any other configuration to make it work?

**Comment by gfosco** [comment]
Hmm.. This is a 2 year old sample, and not maintained, so this probably isn't the answer you're looking for, but... try putting the contents of your css file into a style tag in cloud/views/_header.ejs
